name: Docker Build
# Workflow checks that docker build works

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/midnightntwrk/substrate-telemetry

jobs:
  set-variables:
    name: Set variables
    runs-on: ubuntu-24.04
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Define version
        id: version
        run: |
          export COMMIT_SHA=${{ github.sha }}
          export COMMIT_SHA_SHORT=${COMMIT_SHA:0:8}
          export REF_NAME=${{ github.ref_name }}
          export REF_SLUG=${REF_NAME//\//_}
          if [[ ${REF_SLUG} == "main" ]]
          then
            echo "VERSION=${REF_SLUG}-${COMMIT_SHA_SHORT}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${REF_SLUG}" >> $GITHUB_OUTPUT
          fi
          echo "set VERSION=${VERSION}"

  build_backend:
    name: Build backend docker image
    runs-on: ubuntu-24.04
    needs: [set-variables]
    env:
      VERSION: ${{ needs.set-variables.outputs.VERSION }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f #v3.12.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Build and push Docker image from main
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 #v6.19.2
        with:
          context: backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}-backend:${{ env.VERSION }}

  build_frontend:
    name: Build frontend docker image
    runs-on: ubuntu-24.04
    needs: [set-variables]
    env:
      VERSION: ${{ needs.set-variables.outputs.VERSION }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f #v3.12.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Build and push Docker image from main
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 #v6.19.2
        with:
          context: frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}-frontend:${{ env.VERSION }}
